[package]
name = "pyext-rusty"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]

[lib]
name = "rusty"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.2"
features = ["extension-module"]
